kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-database-local
  namespace: data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi