# apiVersion: v1
# data:
#   .dockerconfigjson: <encrypted string with .docker/config.json file contents>
# kind: Secret
# metadata:
#   name: regcred
#   namespace: front
# type: kubernetes.io/dockerconfigjson
# ---
# apiVersion: v1
# data:
#   .dockerconfigjson: <encrypted string with .docker/config.json file contents>
# kind: Secret
# metadata:
#   name: regcred
#   namespace: back
# type: kubernetes.io/dockerconfigjson
# ---
apiVersion: v1
data:
  POSTGRES_DB: ZHRzLWt1YmU=
  POSTGRES_PASSWORD: ZHRzLWt1YmU=
  POSTGRES_USER: ZHRzLWt1YmU=
kind: Secret
metadata:
  name: db
  namespace: back
type: Opaque
---
apiVersion: v1
data:
  POSTGRES_DB: ZHRzLWt1YmU=
  POSTGRES_PASSWORD: ZHRzLWt1YmU=
  POSTGRES_USER: ZHRzLWt1YmU=
kind: Secret
metadata:
  name: db
  namespace: data
type: Opaque