kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-database
  namespace: data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/dtsetserava/data" # Make sure to create a folder to mount volume