apiVersion: v1
data:
  init.sql: |-
    -- create a table
    CREATE TABLE IF NOT EXISTS person (
      id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
      last_name TEXT NOT NULL,
      phone_number TEXT NOT NULL
    );
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: db-config
  namespace: back
